# -*- coding: utf-8 -*-
"""10th_2a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZE5Y0-wQM30ZaDl2H4pBWRil-aCJstdq
"""

#실습8-1
import datetime as dt

now = dt.datetime.now()
print(f'오늘의 날짜: {now.year}년 {now.month}월 {now.day}일')
print(f"현재시간: {now.hour+9}시 {now.minute}분 {now.second}초")

'''
if now.hour+9>12:
  print(f"오후 {now.hour+9-12}시 {now.minute}분 {now.second}초")
else:
  print(f"오전 {now.hour+9}시 {now.minute}분 {now.second}초")
  '''

#실습 8-2

import datetime as dt

today = dt.date.today()
print(f'오늘은 {today.year}년 {today.month}월 {today.day}일입니다')

bday = dt.datetime(2026, 2, 20)
gap = bday - dt.datetime.now()

print(f'2026년 생일까지는 {gap.days}일 {gap.seconds // 3600}시간 남았습니다.')

#실습 8-3

import datetime as dt

now = dt.datetime.now()
thousand_days = dt.timedelta(days=1000)
plus_thousand = now + thousand_days
print(f'오늘 ({now.year}년 {now.month}월 {now.day}일)으로부터 1000일 후는 {plus_thousand.year}년 {plus_thousand.month}월 {plus_thousand.day}일입니다.')

#2
y,m,d=map(int, input("처음으로 사귄 연도와 월, 일을 입력하시오 ").split())
start_date = dt.datetime(y, m, d)
anniv = dt.timedelta(days=100)
anniv = start_date + anniv
print(f'100일 기념일은: {anniv.year}년 {anniv.month}월 {anniv.day}일 입니다.')

import random as rd
numlist=[1,2,3,4,5]
rd.shuffle(numlist)
print(numlist)
print(rd.choice(numlist))
rd.sample(numlist, 3)

#실습 8-4

import random as rd

randlist=[rd.randrange(0,101,5),rd.randrange(0,101,5),rd.randrange(0,101,5)]
print(f"0에서 100 이하의 정수 중에서 5의 배수: {randlist}")


print(f"1에서 10 사이의 임의의 정수: {rd.sample(range(1, 11), 3)}")