# -*- coding: utf-8 -*-
"""10th_1a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljcldrRKVtrdBQ8XIr0_IemHfKXksGCz
"""

f = open('file_write_5num.py', 'w')
for i in range(5):
    num = input(f"{i+1}번째 숫자 입력: ")
    f.write(num + '\n')
f.close()
print("파일 저장 완료!\n")

try:
    f = open('file_read_5num.py', 'r')
    lines = f.readlines()
    for line in lines:
        print(line, end='')
    f.close()
except UnicodeDecodeError:
    print("UnicodeDecodeError 발생!")
    print("한글이 포함된 파일은 UTF-8 인코딩이 필요합니다.\n")

try:
    f = open('file_read_5num.py', 'r', encoding='UTF8')
    lines = f.readlines()
    for line in lines:
        print(line, end='')
    f.close()
    print("\n파일 읽기 성공!\n")
except FileNotFoundError:
    print("파일을 찾을 수 없습니다.\n")

filename = input("읽을 파일 이름을 입력하세요: ")
try:
    f = open(filename, 'r', encoding='UTF8')
    lines = f.readlines()
    for line in lines:
        print(line, end='')
    f.close()
except FileNotFoundError:
    print(f"FileNotFoundError: '{filename}' 파일을 찾을 수 없습니다!")
    print("안전한 코딩은 중요하다! 예외처리가 필요하다!!\n")

filename = input("읽을 파일 이름을 입력하세요: ")
try:
    f = open(filename, 'r', encoding='UTF8')
    lines = f.readlines()
    print("파일 내용:")
    for line in lines:
        print(line, end='')
    f.close()
except FileNotFoundError as e:
    print(f"파일을 열 수 없습니다: {e}")
    import sys
    sys.exit(1)  # 프로그램 종료
print("\n")

#try-finally

try:
    f = open('example.txt', 'w', encoding='UTF8')
    f.write('안녕하세요\n')
    f.write('파이썬 파일 입출력입니다.\n')
    print("파일 쓰기 완료")
finally:
    f.close()
    print("파일이 정상적으로 닫혔습니다.\n")

#with 문을 사용한 간편한 파일 처리

with open('example_with.txt', 'w', encoding='UTF8') as f:
    f.write('with 문을 사용하면\n')
    f.write('자동으로 파일이 닫힙니다.\n')
    f.write('finally절이 필요 없습니다!\n')
print("with 문: 파일이 자동으로 닫혔습니다.\n")

#with문으로 웹페이지 접

try:
    from urllib.request import urlopen

    url = 'https://www.python.org'
    with urlopen(url) as response:
        html = response.read()
        print(f"웹페이지 크기: {len(html)} bytes")
        print(f"상태 코드: {response.status}")
        print("웹페이지 접속 및 자동 종료 완료!")
except Exception as e:
    print(f"웹페이지 접근 중 오류 발생: {e}")

print("\n" + "=" * 50)
print("모든 예제 실행 완료!")
print("=" * 50)