# -*- coding: utf-8 -*-
"""11th_2a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIQTZHxXo72s8UJMQsEup94BzkLWA5_i
"""

class Car:
  def __init__(self, model, color="black"):
    self.model=model
    self.color=color
  # driver 메서드가 driver_name을 매개변수로 받을 수 있도록 수정합니다.
  def driver(self, driver_name=""):
    if driver_name:
      print(f"{driver_name}이(가) {self.model} 주행")
    else:
      print(f"{self.model} 주행")

mycar=Car("Sonata")

#실습

class Dog:
  def __init__(self, name):
    self.name=name
  def bark(self):
    print(f"월월")
  def __str__(self):
    return f"Dog(name={self.name})"
my_dog=Dog('Jindo')
my_dog.bark()
print(f"my_dog의 정보: {my_dog}")

class Car:
  def __init__(self, name, age):
    self.__name=name
    self.__age=age
  def __str__(self):
    return f"Car(name={self.name}, age={self.age})"
  def meow(self):
    print(f"{self.name}가 야옹야옹")
  def set_age(self, age):
    if age>0:
      self.__age=age
  def get_age(self):
    return self.__getattribute__age
nabi=Car('나비', 2)
print(nabi)
nabi.meow()
nabi.name="멍멍이"
nabi.age-=5
print(nabi)

class Student:
  def __init__(self, name, score=0):
    self.name=name
    self.__score=score
  def set_score(self, score):
    self.__score=score
  def get_score(self):
    return self.__score
  def __str__(self):
    return f"Student(name={self.name}, score={self.__score})"

s1=Student("이소민")
s1_sc=int(input("점수 입력: "))
s1.set_score(s1_sc)
print(s1)

class Student:
  def __init__(self, name, code, kor=0, eng=0, math=0):
    self.name=name
    self.code=code
    self.__kor=kor
    self.__eng=eng
    self.__math=math
  def set_kor(self, kor):
    self.__kor=kor
  def set_eng(self, eng):
    self.__eng=eng
  def set_math(self, math):
    self.__math=math
  def get_kor(self):
    return self.__kor
  def get_eng(self):
    return self.__eng
  def get_math(self):
    return self.__math
  def get_avg(self):
    return (self.__kor+self.__eng+self.__math)/3
  def get_sum(self):
    return (self.__kor+self.__eng+self.__math)
  def __str__(self):
    return f"이름: {self.name}, 학번: {self.code}"

s1=Student("김이박", 251234)
s1.set_kor(int(input(f"{s1.name}의 국어과목 점수를 입력하시오: ")))
s1.set_eng(int(input(f"{s1.name}의 영어과목 점수를 입력하시오: ")))
s1.set_math(int(input(f"{s1.name}의 수학과목 점수를 입력하시오: ")))
print(s1)
print(f"총점: {s1.get_sum()}, 평균: {s1.get_avg():.2f}")

@학생정보