# -*- coding: utf-8 -*-
"""11th_1a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NYSYmN6__sNfOT_jPskAn9w4nxJbe0S
"""

#실습8-5 로또번호만들기 (1)

import random as rd

print("이번 주의 추천 로또 번호")
for i in range(5):
  lotto = rd.sample(range(1,46),6)
  lotto.sort()
  print(lotto)

class Cat:
  def meow(self):
    print("냥냥~~")
nabi=Cat()
nabi.meow()

class Dog:
  def bark(self):
    print("멍멍~~")
my_dog=Dog()

my_dog.bark()

class Cat:
  def __init__(self, name, color='흰색'):
    self.name=name
    self.color=color
nero=Cat('네로')
print(nero.name, nero.color)

class Dog:
  def __init__(self, name):
    self.name=name
  def bark(self):
    print("멍멍~~!!")

my_dog=Dog("Jindo")
my_dog.bark()

