# -*- coding: utf-8 -*-
"""12th_2a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWXKtyBEjbABksh4OSpZi5HggYmhyss4
"""

import numpy as np

b = np.arange(0, 10)
print(f"array[{b.tolist()}]")

import numpy as np

c = np.arange(0, 10, 2)
print(f"array[{c.tolist()}]")

print(f"c.shape: {c.shape}")
print(f"c.ndim: {c.ndim}")
print(f"c.dtype: {c.dtype}")
print(f"c.size: {c.size}")
print(f"c.itemsize: {c.itemsize}")

import numpy as np

a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print(f"a=array[{a}]")

import numpy as np

a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
print(f"최댓값: {a.max()}")
print(f"최솟값: {a.min()}")
print(f"평균: {a.mean()}")

import numpy as np

b=np.random.randint(0,100,10)
print(f"b={b}")
print(f"최댓값: {b.max()}")
print(f"최솟값: {b.min()}")
print(f"평균: {b.mean()}")

import numpy as np

a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
b=np.random.randint(0,100,10)
c=np.append(a,b)
print(f"c={c}")

import numpy as np

a = np.arange(1, 10).reshape(3, 3)
print(f"a=\n{a}")
b = np.full((3,3), 2)
print(f"b=\n{b}")
print(f"1)a+b={a+b}")
print(f"2)a-b={a-b}")
print(f"3)a*b={a*b}")
print(f"4)a/b={a/b}")
print(f"5)a@b={a@b}")
print(f"6)a**b={a**b}")





