# -*- coding: utf-8 -*-
"""12th_1a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IjqTb_dgw4ccgdlpyKFdWKJlIRqwvsd
"""

#실습: mul()과 truediv()메소드를 이용하여 두 벡터의 곳셈과 나눗셈 기능을 구현해라
class Vector2D:
  def __init__(self, x, y):
    self.x = x
    self.y = y
  def __mul__(self, other):
    return Vector2D(self.x * other.x, self.y * other.y)
  def __truediv__(self, other):
    return Vector2D(self.x / other.x, self.y / other.y)
  def __str__(self):
    return f"({self.x}, {self.y})"

v1 = Vector2D(30,40)
v2 = Vector2D(10,20)
print(f"v1*v2={v1*v2}")
print(f"v1/v2={v1/v2}")

class Person:
  def __init__(self, name, score):
    self.name = name
    self.score = score

class Student(Person):
  def __init__(self, id, name, score):
    self.name = name
    self.score = score
    self.id = id

  def grade(self, score):
    if score >= 70:
      return "합격"
    else:
      return "불합격"

std1 = Student("20151234", "홍길동", 80)
std2 = Student("20151485", "김유신", 8)

print(f"id {std1.id} {std1.name}은 {std1.grade(std1.score)}입니다.")
print(f"id {std2.id} {std2.name}은 {std2.grade(std2.score)}입니다.")

class University:
  school_name = "전남대"
  def __init__(self, year):
    self.year = year
  def info(self):
    return f"{self.year}년에 개교한 {University.school_name}"

class College(University):
  def __init__(self, year, name, dept):
    super().__init__(year)
    self.name = name
    self.dept = dept
  def c_info(self, stdnum):
    return f"{stdnum}명"

c1 = College(1964, "AI융합대학", "인공지능")
c2 = College(1964, "인문대학", "국어국문학과")

print(f"{c1.info()} {c1.name} {c1.dept} 학생수는 {c1.c_info(100)}이다.")
print(f"{c2.info()} {c2.name} {c2.dept} 학생수는 {c2.c_info(150)}이다.")