# -*- coding: utf-8 -*-
"""5th_1a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAhNS59N7oKnRV-C0NGR9i0YiIeLwDi6

#예제 5-4
사용자에게 정수를 입력받아 양수인지, 0인지, 음수인지 판별하는 코드를 중첩 if ~
else문을 사용하여 작성해보자.
"""

num = int(input("정수 입력: "))
if num >= 0:
  if num == 0:
    print("0입니다.")
  else:
    print("양수입니다.")
else:
  print("음수입니다.")

"""주어진 코드는 멤버십과 주문금액에 따라 배달비 부과 여부를 출력하는
프로그램의 일부이다.
주문금액과 멤버십 회원여부를 입력받아 , 최소 주문 금액이 20000원
이상이면서 멤버십회원이면 “배달비 무료+ 멤버십할인” 적용을 출력하고,
멤버십회원이 아니면 “배달비 무료(멤버십 없음)”을 출력, 최소주문금액을
만족하지 못한 경우는 “배달비 3000원 부과”를 출력하는 프로그램을 중첩if를
활용하여 완성하시오. (멤버십 회원여부는 boolean값으로 입력받기)
"""

order_price=int(input("주문 금액을 입력하세요: "))
membership=input("멤버십 회원입니까?(y/n): ").lower()
if membership in ["y","yes","1","true"]:
  is_member=True
else:
  is_member=False
if order_price >= 20000:
  if is_member:
    print("배달비 무료+ 멤버십할인")
  else:
    print("배달비 무료(멤버십 없음)")
else:
  print("배달비 3000원 부과(최소주문금액 미충족)")

a=["apple","banana","peach"]
b=["cinamon roll", "cheesecake", "tiramisu"]
c=a+b
print(c)
c[-2:-1]="tanghuru","mango"
print(c)
c.pop()
print(c)

student=["홍길동","허난설현","이균"]
student.append("허균")
print(student)
student.append("허균")
print(student)
print(student.count("허균"))
student.remove("홍길동")
print(student)
student.sort()
print(student)

t=tuple(range(1,10,2))
t