# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7VwKpKXU8WJCHPSlwP6DNupSolwnCvI
"""

dic={"고양이":1,
      "가나디":2}
print(dic)

# Multiple keys with the same value - this is not directly possible in Python dictionary syntax
# You would need to assign the value to each key individually:
dic_multiple_keys = {
    "고양이": 1,
    "가나디": 1
}
print(dic_multiple_keys)

# Using a list as a key - this will cause an error because lists are mutable and cannot be used as dictionary keys.
# You can use an immutable type like a tuple as a key instead.
try:
    dic_list_key = {
        ["고양이", "가나디"]: 1 # This will raise a TypeError
    }
    print(dic_list_key)
except TypeError as e:
    print(f"Error: {e}")

# Using a tuple as a key (immutable and works)
dic_tuple_key = {
    ("고양이", "가나디"): 1
}
print(dic_tuple_key)

# Using a tuple with multiple elements as a key
dic_multi_element_tuple_key = {
    ("고양이", "가나디", "다람쥐"): 1
}
print(dic_multi_element_tuple_key)
print(dic_multi_element_tuple_key.keys())
print(dic_multi_element_tuple_key.count("고양이"))

# Example dictionary
my_dict = {"a": 1, "b": 2, "c": 1, "d": 3, "e": 2, "f": 1}

# How to count the occurrences of a specific value (e.g., the number 1)
count_of_one = list(my_dict.values()).count(1)
print(f"Count of value 1: {count_of_one}")

# How to count the occurrences of each value using collections.Counter
from collections import Counter

value_counts = Counter(my_dict.values())
print(f"Counts of all values: {value_counts}")

dic={"강감찬":"귀주대첩","을지문덕":"살수대첩","세종대왕":"집현전"}
print(dic)
dic["서희"]="강동6주"
print(dic)
dic["세종대왕"]="한글"
print(dic)
if "을지문덕" in dic:
  del dic["을지문덕"]
print(dic)

animals={"강아지":"dog","고양이":"cat","코끼리":"elephant"}
while True:
    name=input("동물이름: ")
    if name in animals:
        print(f"{name}은/는 영어로 {animals.get(name)}입니다.")
    else:
        print("사전에 없는 단어입니다.")
        break

"""예제 5-6. 주소록에 친구를 등록하고, 친구를 이름으로 검색한 후 연락처를 출력하는
프로그램을 작성하시오. 실행결과를 참고하여 문제를 해결하시오.
1.딕셔너리자료 구조를 사용하여 임의로 친구의 이름과 연락처를 저장한다.
2.딕셔너리에서 전체 친구의 이름만 검색하여 리스트로 변환한 후 출력한다.
3.찾는 친구의 이름은 반복문을 이용하여 사용자로부터 입력받아
처리한다.(변수명은 적절하게 사용하시오.)
4.찾는 친구가 있으면 연락처를 출력하고 없으면 에러 메시지를 출력하고
반복문을 벗어난다.
"""

call={'홍길동':"010-1221-1234","김유신":"010-1111-1111","이순신":"010-1234-1231","김좌진":"010-5555-5678","강감찬":"010-9999-9999"}
while True:
  search=input("search_name>>")
  if search in call:
    print(call.get(search))
  else:
    print("Not Found")
    print("프로그램 종료")
    break

#실습예제 1:1. 어느 식당의 메뉴와 가격은 돈가스 5,000원, 생선가스 5,500원, 우동 2,500원, 초밥
#세트 9,000원이다. 이 메뉴들을 빈 dictionary를 생성한 후, 딕셔너리 자료구조를
#이용하여 저장해보고 각각의 메뉴와 가격을 순차적으로 출력하는 프로그램을
#작성하여 보자.

menu_list = list(menu.items())
print("===================menu===================")
print(menu_list)

#예제03. 현대인들은 축약어를 많이 사용한다. 예를 들어서 "B4(Before)" "TX(Thanks)" "BBL(Be
# Back Later)" "BCNU(Be Seeing You)" "HAND(Have A Nice Day)"와 같은 축약어들이 있다.
# 축약어를 풀어서 일반적인 문장으로 변환하는 프로그램을 작성하여 보자.
answer=""
dic={"TX":"Thanks","BCNU":"Be seeing you","HAND":"Have A Nice Day","BBL":"Be Back Later"}
s=input("번역할 문장을 입력하시오:").split()
for i in s:
  if i in dic:
    answer+=dic.get(i)+" "
  else:
    answer+=i+" "
print(answer)

#예제4: 재고품 관리를 하려고 한다. 비품이 떨어지지 않도록 비품을 3개 이상으로
#유지한다고 할 때, 각각 사야할 비품과 가격, 총 비용을 계산해 출력하여라.

dic={"믹스":[6000,2],"종이컵":[15000,3]}