# -*- coding: utf-8 -*-
"""7th_2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTzXfiTvQ5zqc_S86EBJdteRE0pjpUWQ
"""

def welcome(name="고객"):
  print(name,"님! 환영합니다.")

n=input()
welcome(n)
welcome()

def sumofnum(*n):
  sum=0
  for i in n:
    sum+=i
  print(sum)
sumofnum(*[11,2,3,4,5])

"""크기가 각각 4,5인 튜플원소의 최대값을 구하는 함수를 구현하시오

ex t1=1,2,3,4,5
t2=5,7,9,4
"""

def findMax(*t):
  max=t[0]
  for i in t:
    if max<i:
      max=i
  print(max)
t1=(1,2,3,4,5)
t2=(5,7,9,4)
findMax(*t1)
findMax(*t2)

def info(name,age,gender):
  print(f"이름:{name}\n나이:{age}\n성별:{gender}")

info(name)

def info(**keyargs):
  print(type(keyargs))
  for k,y in keyargs.items():
    print(f"{k}:{y}")

info(name="홍길동",age=20,gender="남")

#학생 점수 정보 -홍길동:87 김유신:60 이순신:90 강감찬:82 서희: 77/85점이상의 점수를 가진 학생을 키워드기반 가변인자를 활용하여 출력하는 함수를 구현하시오
student={'tom':87, 'john':60, 'jane':90, 'rosa':82, 'risa':77}
def print_name(*student_dic):
  print("점수가 85점 이상인 학생:")
  for name,score in student.items():
    if score>=85:
      print(name,"(",score,"점 )",end=" ")

print_name(student)

def scoreInfo(**info):
  result={}
  for k,v in info.items():
    if v>=85:
      result[k]=v
  return result

student={'tom':87, 'john':60, 'jane':90, 'rosa':82, 'risa':77}
print(scoreInfo(**student))
print(scoreInfo(홍길동=24, 제인=24, 로즈=99, 냥냥=76))

def sumOfNum(n):
  if n<0:
    return "없습니다!"
  elif n==1:
    return 1,
  else:
    return n+sumOfNum(n-1)

print(sumOfNum(25))