# -*- coding: utf-8 -*-
"""7th_1A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2d8g7gMy4rJsTQDS6_XJfD_5Fm6YmHO
"""

def printFunc(a):
  print(a*3)
printFunc("babo")

def sn():
  print(f"이름:{name}, 학번:{code}")

name=input("이름을 입력하세요: ")
code=input("학번을 입력하세요: ")
sn()

"""for문을 이용하여 1부터 9까지 출력하는 함수 print19( )를 작성하고 호출해보자."""

def print19():
  for i in range(1,10):
    print(i)

print19()

def gugudan(dan):
  for i in range(9):
    print(f"{dan}*{i+1}={dan*(i+1)}")

gugudan(int(input("단 수를 입력: ")))

"""시작에 해당하는 정수를 입력받아 변수 s에 대입하고, 끝에 해당하는 정수를
입력받아 e에 대입한 후, for문을 이용하여 start부터 end까지 출력하는
함수print_se(start,end)를 작성하고 호출해보자.(단, 입력한 후 변수 s의 값이 변수 e의
값보다 작을 때 만 함수를 호출한다.)
"""

def print_se(s,e):
    for i in range(s,e+1):
      print(i)

start=int(input("시작: "))
end=int(input("끝: "))

if (start<end):
  print_se(start,end)
else:
  print(f"start({start})값이 end({end})보다 큽니다.")

def avg(a1,a2):
  return (a1+a2)/2

def circle_area_circum(radius):
  area=3.14*radius*radius
  circum=2*3.14*radius
  return area, circum
area, circum=circle_area_circum(int(input()))
print("면적:",area)
print("둘레:",circum)

"""추가예제1: 임의의 리스트를 매개변수로 입ㄺ받아 리스트 원소의 최대값을반환하는 함수 구현"""

def findMax(l):
  max=l[0]
  for i in l:
    if i>=max:
      max=i
  return max
findMax([1,2,3,4,5])

"""추가예제2. 문자열을 원소로 하는 임의의 리스트를 매개변수로 받아 리스트원소 문자열과 문자열의 길이를 튜플의 리스트로 리턴하는 함수를 구현하고 테스트하시오."""

def ltotuple(l):
    return [(s, len(s)) for s in l]
ltotuple(["안녕","하","세요!!"])