# -*- coding: utf-8 -*-
"""9th_2A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OlIOUMbibvdgzo-NY6mfv4z-33naIHm
"""

#학번 이름을 저장하고 잇는 stdinfo.txt파일을 생성하시오
f=open("stdinfo.txt","a+")
f.write("20220001 홍길동\n")
f.write("20220002 김철수\n")
f.write("20220003 이영희\n")

from google.colab import drive
drive.mount('/content/drive')

f = open('we_will_rock.txt','r')
lines = f.readlines()
for line in lines:
    print(line.rstrip())
f.close()

#실습3. 1에서 10까지의정수를 저장하는 num10.txt파일을 파일객체의 write()메소드와 for _ in range()구문을사용하여 ㅇ작성하시오

f=open("num10.txt","w")
for i in range(1,11):
  f.write(str(i)+"\n")
f.close()

#실습4. num10.txt파일을 읽어들인 다음 사용자로부터 양의 ㅈㅇ수 (n은 10보다 작은수)을 입력받아 n번째 줄까지 출ㄹ교하근 프로그램을 작서아힛오

f=open("num10.txt","r")
n=int(input("10보다 작은 양의 정수를 입력하시오: "))
if 0<n<=10:
  for i in range(n):
    line=f.readline()
    print(line,end="")
else:
  print("입력받은 수가 정확하지 않습니다.")
f.close()