# -*- coding: utf-8 -*-
"""9th_1A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ss-nii6M8JT_4syGu0SiOlqSVJSLtUD_
"""

#실습예제 7-2 try-except-else문 실습
a=[1,2,3,4,5]
def get(x):
    try:
        num=int(input("a의 요소를 하나 선택하시오.:  "))
    except ValueError:
        print('오류 : 입력 값이 정수나 실수가 아님')
    except IndexError:
        print('오류 : 리스트 범위를 벗어났습니다.')
    else:
        print(f'{num}은 {a.index(num)+1}번째 요소입니다. ')

get(a) # 함수 호출 추가