# -*- coding: utf-8 -*-
"""중간고사.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nomm6_26zlbMKPKbi5VCprku6j5TZpp7
"""

#01. 다음과 같은 과일 리스트가 주어져 있을 때 입력받은 과일 문자열이 리스트 안에 존재하는지 확인하고 주어진 예시대로 출력되도록 프로그램을 구현하시오

l1=["사과","바나나","딸기","포도","오렌지"]
fruit=input("좋아하는 과일>> ")
if fruit in l1:
    print("구매 가능한 과일입니다.")
else:
    print("구매가능한 과일이 아닙니다.")

#02. 사용자로부터 4명의 키를 입력받고, 가장 큰키와 작은 키를 출력하는 프로그램을 구현하시오. 단 빈 리스트를 만들고 for문을 사용하여 4명의 키를 입력받아 리스트에 저장되도록 한 후 최대 최소값을 계산하시오

h_list=[]
for i in range(1,5):
    h=input(f"{i}번째 사람의 키(cm)를 입력하시오: ")
    h_list.append(h)
max_h=h_list[0]
min_h=h_list[0]
for i in h_list:
    if i>max_h:
        max_h=i
    if i<min_h:
        min_h=i
print(f"가장 큰 키: {max_h}cm")
print(f"가장 작은 키: {min_h}cm")

#03. 책 제목을 키로 하고 대출된 횟수와 대출 여부(True:대출중 False: 대출가능)을 튜플형태의 value로 저장하는 도서관 대출 관리 딕셔너리를 생성하시오. 생성된 딕셔너리를 이용하여 현재 대출중인 책들만 출력하는 코드를 작성하고, 대출된 횟수가 5회 이상인 책들 중 대출 가능한 책들만 출력하는 코드를 작성하시오.
book={"Python Basics":(3, True),
      "Machine Learning":(1,True),
      "AI for Everyone":(2,True),
      "Data Science with Python":(5,False)}
borrowed=[]
above5_canborrow=[]

for name, status in book.items():
    if status[1]==True:
        borrowed.append(name)
    if status[0]>=5 and status[1]==False:
        above5_canborrow.append(name)

print("현재 대출 중인 책들:")
for i in borrowed:
    print(f"- {i}")
print("대출 횟수 5회 이상이면서 대출 가능한 책들:")
for i in above5_canborrow:
    print(f"- {i}")

#04. 디폴트 매개변수로 합격 커트라인을 정하고, 가변인자를 사용하여 학생의 점수를 입력받아
# 전체 평균과 합격자수, 불합격자 수를 반환하는 함수 scoreboard1()을 구현하시오.

def scoreboard1(passline=60, **kwargs):
    result={}
    pass_cnt=0
    not_cnt=0
    scoresum=0

    if not kwargs:
        return None

    for name, score in kwargs.items():
        scoresum+=score
        if score>=passline:
            pass_cnt+=1
        else:
            not_cnt+=1

    result['avg']=scoresum/(pass_cnt+not_cnt)
    result['pass_cnt']=pass_cnt
    result['not_cnt']=not_cnt

    return result


print(scoreboard1(passline=70, Kim=70, Park=70, Lee=30, Choi=100))
print(scoreboard1())